#=========================================================================================
#================ Docs: https://github.com/isunjn/serene/wiki ============================
#=========================================================================================

base_url = "https://example.com" # The domain of your site
title = "Mon site"
description = "Ma description"
default_language = "fr"
theme = "serene"
output_dir = "public"
compile_sass = true              # Keep this true
minify_html = true               # Whether to minify html code
build_search_index = false       # Keep this false, search is temporarily unsupported
generate_feed = false            # Whether to generate a feed file in root, read docs for more info about rss feed
feed_filename = "feed.xml"       # The file name of feed, "feed.xml" / "atom.xml" / "rss.xml", read docs for more info
taxonomies = [
    {name = "tags"},             # Keep this
    {name = "categories"}        # Keep this
]

[markdown]
highlight_code = true
extra_syntaxes = []
highlight_theme = "nord"         # The highlight theme, choose one at https://www.getzola.org/documentation/getting-started/configuration/#syntax-highlighting
render_emoji = true
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================
[extra]
name = "Hugo"                    # Your name
id = "Hugo81"                      # Your id/username/handle
bio = "Ma bio"                     # Your bio
avatar = "img/cerise.jpg"       # Your avatar

show_id = true                   # Whether to show your id in homepage
show_projects = true             # Whether to show projects page

#============== Icons, you can choose at https://remixicon.com/ ====
blog_icon = "ri-quill-pen-line"
projects_icon = "ri-compasses-2-line"
home_icon = "ri-user-6-line"
rss_icon = "ri-rss-line"
toc_icon = "ri-menu-2-line"

#============== Social media links =================================
links = [
    {name = "GitHub", icon = "ri-github-line", url = "https://github.com/<your-username>"},
    {name = "Twitter", icon = "ri-twitter-line", url = "https://twitter.com/<your-username>"},
    {name = "Email", icon = "ri-mail-line", url = "mailto:<your-email-address>"}
    # Your can add more links
]

#============== Feed ===============================================
feed_in_blog_section = true      # Whether to make feed file in blog section, url will be https://example.com/blog/feed.xml, read docs for more info about rss feed

#============== Some feature switches ================================
toc = true                       # Whether to show Table-Of-Contents [Can be overridden by page config]
blur_effect = true               # Whether to turn on blur effect on navigation bar
back_to_top_button = true        # Whether to show Back-To-Top button
progress_bar = true              # Whether to show reading progress bar
cc_license = false               # Whether to show Creative-Commons statement [Can be overridden by page config]
cc_license_statement = "This work is licensed under [CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/)."  # The Creative-Commons statement
outdate_warn = false             # Whether to show outdate warning [Can be overridden by page config]
outdate_warn_days = 120          # How many days will a post be outdated [Can be overridden by page config]
outdate_warn_text_before = "Note: This article was last updated "
outdate_warn_text_after = " days ago and may be out of date."

#============== Footer =============================================
footer_copyright_name = "Hugo81"
footer_copyright_year = "2022"
# footer_custom = "xxxxxxxx"
footer_credits = true            # Whether to show "Powered by Zola and Serene" in footer
