[[project]]
name = "Mon projet un"
desc = "Description"
links = [
	{name = "Lien 1", url = "https://www.example.com/"},
	{name = "Lien 2", url = "https://www.example.com/2"}
]

[[project]]
name = "Mon projet 2"
desc = "Description 2"
links = [
	{name = "Lien 2-1", url = "https://www.example.com/"},
	{name = "Lien 2-2", url = "https://www.example.com/2"}
]
